name: .NET Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x' # Reemplaza con tu versión específica de .NET

    - name: Restore dependencies
      run: cd SocialMedia && dotnet restore

    - name: Build
      run: cd SocialMedia && dotnet build --configuration Release --no-restore
